"""add author to quote

Revision ID: 4afe2dfd671d
Revises: c5080a0b4b01
Create Date: 2025-04-26 16:44:57.937501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4afe2dfd671d'
down_revision: Union[str, None] = 'c5080a0b4b01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.alter_column('text',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_index('ix_quotes_author')
        batch_op.drop_index('ix_quotes_text')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.create_index('ix_quotes_text', ['text'], unique=False)
        batch_op.create_index('ix_quotes_author', ['author'], unique=False)
        batch_op.alter_column('text',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
